version: "3.9"
services:

  tools:
    build: .
    image: mertcingoz/udmi-cli
    stdin_open: true
    tty: true
    working_dir: /app
    volumes:
      - type: bind
        source: udmi
        target: /app
      - type: bind
        source: ~/.config
        target: /root/.config
    environment:
      GOOGLE_CLOUD_PROJECT: udmi-demo-01
      GOOGLE_CLOUD_REGION: us-central1
      GOOGLE_CLOUD_REGISTRY: ZZ-TRI-FECTA
