version: "3.9"
services:

  tools:
    build:
      context: .
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
    image: mertcingoz/udmi-cli
    stdin_open: true
    tty: true
    working_dir: /app
    volumes:
      - type: bind
        source: udmi
        target: /app
      - type: bind
        source: ~/.config
        target: /root/.config
      - type: bind
        source: scripts
        target: /scripts
    environment:
      UDMI_REPO: ${UDMI_REPO}
      UDMI_VERSION: ${UDMI_VERSION}
      IOT_PROVIDER: ${IOT_PROVIDER}
      GOOGLE_CLOUD_PROJECT: ${GOOGLE_CLOUD_PROJECT}
      GOOGLE_CLOUD_REGION: ${GOOGLE_CLOUD_REGION}
      GOOGLE_CLOUD_REGISTRY: ${GOOGLE_CLOUD_REGISTRY}
      UDMI_REFLECT_REGISTRY: ${UDMI_REFLECT_REGISTRY}
      UDMI_ALT_REGISTRY: ${UDMI_ALT_REGISTRY}
      UDMI_PUBSUB: ${UDMI_PUBSUB}
