version: "3.9"
services:

  tools:
    build:
      context: .
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
    image: mertcingoz/udmi-cli
    stdin_open: true
    tty: true
    working_dir: /udmi
    env_file: .env
    volumes:
      - type: bind
        source: udmi
        target: /udmi
      - type: bind
        source: ~/.ssh
        target: /root/.ssh
